package authapp

import (
	"fmt"
	"sort"
	"strings"
)

// Publishing the SNI list to a shared front (Spec #111, acme-proxied ingress).
//
// With `--route-ingress acme-proxied` some other box owns the host's :80/:443
// and forwards Public Route traffic here by SNI, TLS handshake intact. That
// front therefore needs to know WHICH hostnames to forward — and the Auth App
// is the only party that knows, because it is where Routes are published.
//
// So the list is generated, not hand-maintained: on every Caddyfile
// regeneration the Auth App renders the fragment below and pushes it into the
// front instance over the same Incus admin socket it already uses for per-Route
// proxy devices, then reloads the front's Caddy. The front imports the fragment
// once and never needs another edit:
//
//	servers :443 {
//	    listener_wrappers {
//	        layer4 {
//	            import /etc/caddy/sandcastle/*.caddy
//	        }
//	        tls
//	    }
//	}
//
// One fragment per install (named by the install prefix), so several
// Sandcastle installs can share one front without colliding.

// FrontFragmentHeader marks the generated file. Anything under it is rewritten
// on the next publish, delete, or reconcile pass.
const FrontFragmentHeader = "# Generated by the Sandcastle Auth App — do not edit."

// RenderFrontSNIFragment renders the caddy-l4 snippet a shared front imports:
// a named TLS-SNI matcher listing every published Route Hostname, and a route
// that proxies those connections to this appliance untouched.
//
// matcher is the matcher-set name (unique per install). upstream is this
// appliance's address on the front's network. hosts are the published Route
// Hostnames; with none, the fragment is header-only — a front that imports it
// then forwards nothing, which is exactly right for an install with no Routes.
//
// Deterministic: hosts are sorted and de-duplicated, so an unchanged registry
// renders byte-identical output and the front is not reloaded for nothing.
func RenderFrontSNIFragment(matcher, upstream string, hosts []string) string {
	var b strings.Builder
	b.WriteString(FrontFragmentHeader + "\n")
	b.WriteString("# Public Route hostnames of this Sandcastle install. Their certificates are\n")
	b.WriteString("# issued inside the appliance, so this front must forward the TLS handshake\n")
	b.WriteString("# without terminating it.\n")

	clean := make([]string, 0, len(hosts))
	seen := map[string]bool{}
	for _, host := range hosts {
		host = strings.ToLower(strings.Trim(strings.TrimSpace(host), "."))
		if host == "" || seen[host] {
			continue
		}
		seen[host] = true
		clean = append(clean, host)
	}
	sort.Strings(clean)
	if len(clean) == 0 {
		b.WriteString("# (no routes published)\n")
		return b.String()
	}

	matcher = strings.TrimSpace(matcher)
	if matcher == "" {
		matcher = "sandcastle_routes"
	}
	fmt.Fprintf(&b, "@%s tls sni %s\n", matcher, strings.Join(clean, " "))
	fmt.Fprintf(&b, "route @%s {\n\tproxy tcp/%s\n}\n", matcher, strings.TrimSpace(upstream))
	return b.String()
}

// FrontMatcherName is the matcher-set name for an install's fragment. Derived
// from the install prefix so two installs sharing a front cannot collide (a
// duplicate matcher name is a hard Caddyfile parse error, which would take the
// front down for everyone).
func FrontMatcherName(prefix string) string {
	prefix = strings.TrimSpace(strings.ToLower(prefix))
	safe := strings.Map(func(r rune) rune {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			return r
		default:
			return '_'
		}
	}, prefix)
	safe = strings.Trim(safe, "_")
	if safe == "" {
		return "sandcastle_routes"
	}
	return "sandcastle_" + safe
}
