package domain

import (
	"bytes"
	"context"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

const (
	IANAAlphaTLDURL          = "https://data.iana.org/TLD/tlds-alpha-by-domain.txt"
	DefaultTLDSnapshotOutput = "internal/domain/tld_snapshot_generated.go"
)

type RefreshRequest struct {
	SourceURL  string `json:"sourceURL"`
	OutputPath string `json:"outputPath"`
	DryRun     bool   `json:"dryRun"`
}

type RefreshResult struct {
	SourceURL  string   `json:"sourceURL"`
	OutputPath string   `json:"outputPath"`
	Count      int      `json:"count"`
	TLDs       []string `json:"tlds,omitempty"`
	Written    bool     `json:"written"`
}

func RefreshTLDSnapshot(ctx context.Context, client *http.Client, request RefreshRequest) (RefreshResult, error) {
	sourceURL := strings.TrimSpace(request.SourceURL)
	if sourceURL == "" {
		sourceURL = IANAAlphaTLDURL
	}
	outputPath := strings.TrimSpace(request.OutputPath)
	if outputPath == "" {
		outputPath = DefaultTLDSnapshotOutput
	}
	if client == nil {
		client = &http.Client{Timeout: 30 * time.Second}
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, sourceURL, nil)
	if err != nil {
		return RefreshResult{}, err
	}
	resp, err := client.Do(req)
	if err != nil {
		return RefreshResult{}, err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return RefreshResult{}, fmt.Errorf("fetch IANA TLD list: %s", resp.Status)
	}
	tlds, err := ParseIANAAlphaTLDs(resp.Body)
	if err != nil {
		return RefreshResult{}, err
	}
	source, err := GenerateTLDSnapshotSource(tlds)
	if err != nil {
		return RefreshResult{}, err
	}
	result := RefreshResult{
		SourceURL:  sourceURL,
		OutputPath: outputPath,
		Count:      len(tlds),
		TLDs:       tlds,
		Written:    !request.DryRun,
	}
	if request.DryRun {
		return result, nil
	}
	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		return RefreshResult{}, err
	}
	if err := os.WriteFile(outputPath, source, 0o644); err != nil {
		return RefreshResult{}, err
	}
	return result, nil
}

func ParseIANAAlphaTLDs(reader io.Reader) ([]string, error) {
	content, err := io.ReadAll(reader)
	if err != nil {
		return nil, err
	}
	seen := map[string]bool{}
	for _, line := range strings.Split(string(content), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		label := strings.ToLower(line)
		if !validTLDLabel(label) {
			return nil, fmt.Errorf("invalid TLD label %q", line)
		}
		seen[label] = true
	}
	if len(seen) == 0 {
		return nil, fmt.Errorf("IANA TLD list is empty")
	}
	tlds := make([]string, 0, len(seen))
	for tld := range seen {
		tlds = append(tlds, tld)
	}
	sort.Strings(tlds)
	return tlds, nil
}

func GenerateTLDSnapshotSource(tlds []string) ([]byte, error) {
	var builder bytes.Buffer
	builder.WriteString("// Code generated by sandcastle admin tld refresh; DO NOT EDIT.\n")
	builder.WriteString("package domain\n\n")
	builder.WriteString("var publicTLDs = map[string]bool{\n")
	for _, tld := range tlds {
		if !validTLDLabel(tld) {
			return nil, fmt.Errorf("invalid TLD label %q", tld)
		}
		fmt.Fprintf(&builder, "\t%q: true,\n", strings.ToLower(tld))
	}
	builder.WriteString("}\n")
	return format.Source(builder.Bytes())
}

func validTLDLabel(label string) bool {
	if label == "" || strings.HasPrefix(label, "-") || strings.HasSuffix(label, "-") {
		return false
	}
	for _, r := range label {
		if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
			return false
		}
	}
	return true
}
